name: Unit Test, Build, and Push

on: 
  push:
    branches: 
      - '*'
    tags:
      - '*'
  pull_request:
    branches: 
      - '*'
    tags:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Code format
        run: |
          # Run gofmt, add line numbers, and perform diff to get return code.
          diff -u <(echo -n) <(gofmt -d -s .)
          go fmt 
      - name: go vet
        run: go vet
      - name: Unit tests
        run: go test -race
      - name: Test coverage
        run: |
          go test "-coverprofile=coverage.out"
          go tool cover "-func=coverage.out"

  docker:
    needs: test
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dirtysoc/supermarket-api

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.output.labels }}